### ISSUE TITLE
Warning about missing google-services.json and a deprecated task/functionname

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#14]
Warning message below:

Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

**Comment by CodeCombiner** [comment]
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)`. This seems to be produced by Fabric Crashlytics android gradle plugin. Fabric seems to be fixed it according to their post but the warning seems to be present still. I think is will be fixed with next versions coming.
https://stackoverflow.com/a/49577707

**Comment by CodeCombiner** [comment]
`Could not find google-services.json` seems to be annoying bug without any issues. It raises if the file is not found in all config specific directories but as well it does not dismiss warnings if the file is found in one of required directory.
https://stackoverflow.com/a/49425784

**Comment by rampr** [comment]
Thanks for the updates :) So these can be ignored then
