### ISSUE TITLE
Support for customisation in freshchat

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#48]
Example -> https://github.com/hashcube/freshchat/pull/13

**Comment by CodeCombiner** [comment]
Since we have moved to gradle style dependencies and there are no libraries projects (with source code) in gradle project anymore, I think it is required to create 1 more injector for styles.xml. It will copy customized android style `Widget.Freshchat.FAQList` or it's parameters into styles.xml like gradle settings are copied/overridden in gradle files.

**Comment by rampr** [comment]
okay, makes sense

**Comment by rampr** [comment]
Will verify and close

**Comment by CodeCombiner** [comment]
Please test, made new PR
https://github.com/hashcube/freshchat/pull/15
