### ISSUE TITLE
Release build doesn't run

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#95]
Release build doesn't run on the device and throws the following error

04-15 15:09:34.974  3395  3456 I ActivityManager: Start proc 14721:com.hashcube.sqmtest/u0a1018 for embryo com.hashcube.sqmtest
04-15 15:09:34.974  3395  3456 D Embryo_Uterus: Embryo created.com.hashcube.sqmtest, pid=14721
04-15 15:09:35.057  3395 20586 D EmbryoManager: Embryo attached, pid=14721
04-15 15:09:35.292 14721 14721 I chatty  : uid=11018(com.hashcube.sqmtest) expire 11 lines
04-15 15:09:35.294  3395 11956 D Embryo_Uterus: get preload status from 14721, success=true
04-15 15:10:19.196  3395  8641 D EmbryoManager: Embryo claimed. com.hashcube.sqmtest, pid=14721
04-15 15:10:19.296 14721 15039 I chatty  : uid=11018(com.hashcube.sqmtest) AsyncTask #1 expire 2 lines
04-15 15:10:19.377 14721 14721 I chatty  : uid=11018(com.hashcube.sqmtest) expire 239 lines
04-15 15:10:19.488 14721 15036 I chatty  : uid=11018(com.hashcube.sqmtest) Measurement Wor expire 3 lines
04-15 15:10:19.500 14721 14721 F libc    : tealeaf/src/main/jni/AssetExtractor.cpp:25: static void tns::AssetExtractor::ExtractAssets(JNIEnv *, jobject, jstring, jstring, jstring, jboolean): assertion "z != nullptr" failed
04-15 15:10:19.681 14721 14721 I chatty  : uid=11018(com.hashcube.sqmtest) expire 21580 lines
04-15 15:10:30.982 14721 14721 I chatty  : uid=11018(com.hashcube.sqmtest) expire 13019 lines
04-15 15:10:37.682 14721 14721 E libc++abi: terminating with uncaught exception of type tns::NativeScriptException
04-15 15:10:37.683 14721 14721 E libc++abi: terminate_handler unexpectedly threw an exception
04-15 15:10:37.683 14721 14721 E libc++abi: terminating with uncaught exception of type tns::NativeScriptException
04-15 15:10:37.684 14721 14721 E libc++abi: terminate_handler unexpectedly threw an exception
04-15 15:10:37.684 14721 14721 E libc++abi: terminating with uncaught exception of type tns::NativeScriptException

**Comment by CodeCombiner** [comment]
The issue seems to be in this parameter shrinkResources = true, it must be set to false in release build in gradle.

Just go to android_project/app/build.gradle , buildTypes section

buildTypes {
release {
`shrinkResources false`
`useProguard true`
minifyEnabled true
proguardFiles 'proguard-rules.pro'
manifestPlaceholders = [appName: "SQ Test"]

}
debug {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
manifestPlaceholders = [appName: "SQ Test debug"]
}
}

I will add this line in next commit
